### ISSUE TITLE
FInal release - project dead?

### ISSUE THREAD

**Issue by enoch85** [bugfishtm/Bind9-Web-Manager#2]
Just found this looking for a GUI to implement for our First-Line support... Saw that you made a "final release" - does that mean this project is dead?

**Comment by bugfishtm** [comment]
Hi there,

Thank you for reaching out. The project is still very much active, and the repository is maintained. You can continue to use this version for as long as you need, and I will address any issues that are reported.

The "Final Release" label means:
- There are currently no known bugs in the software.
- It has been thoroughly tested on various systems, and all known conflicts have been resolved.
- We are developing a CMS and plan to integrate the Bind9 Web Manager Software into it. This new module will offer more functionalities for hosting and domain management in productive environments.
- This is the final release for Version 3. Version 4 will be a CMS-related upgrade to the Bind9 Web Manager Software.

If you encounter any issues with version 3.X, we will provide updates as necessary upon request. Therefore, you can continue to use version 3.X for as long as you need.

For enhanced functionalities in hosting environments, you may consider upgrading to version 4 when it becomes available. However, please note that there will be no compatibility between versions 3 and 4.

If you're planning to try this software, I recommend using a test VM first. This software is primarily designed for replication and replication management. While you can use it as a GUI to view Bind9 records on local and external servers, be cautious with the cronjob. The cronjob may create additional Bind9 files for replication configuration.

As far as I know, the software will not disrupt a running configuration or overwrite any configuration files. The crucial functionality is within the cronjob. It may is a bit "messy", because there has been code implemented to support replication server configurations on different Hosting systems [on top] - this lead to small changes over the time.

Use this approach to ensure smooth and safe operation.

Have a great day!

If you still have any questions, do not hesitate :)

**Comment by enoch85** [comment]
Wow, thanks!
